### ISSUE TITLE
Missing description field in Helios calendar

### ISSUE THREAD

**Issue by uiwwebteam** [asdfdotdev/Helios-Calendar#20]
### Steps to reproduce
Go to "http://uiw.edu/calendar, click "Editor Sign In" on left-nav, click "Submit New Event," notice that the "Description" field is missing, though it appears briefly after starting the editor. Submissions will not be allowed without this field having content.
### Expected behavior
On the "Submit..." editor, the "Description" text field should appear.

### Actual behavior
The Description field appears for less than a second then disappears.

### System Information
**Helios Calendar 3.0 / branch**:

**PHP version**:
UNK
**MySQL version**:
UNK
### Additional details
Appears the last update to the files was in 2015.
It looks like the line that I want to see working is /calendar/inc/functions/forms.php at line 669.
<textarea name="eventDescription" id="eventDescription" rows="20" placeholder="'.$hc_lang_submit['PlaceDesc'].'" class="mce_edit"></textarea>
I inherited this from the previous web team, so I'm not familiar with the syntax.
![helios_missing_description](https://user-images.githubusercontent.com/43243654/45496233-96c0bd00-b73a-11e8-8f1d-2a88ebd02e93.png)

**Comment by bklups** [comment]
Change your TinyMCE version (3 or 4)

**Comment by uiwwebteam** [comment]
Benjamin,

Updating/replacing the TinyMCE didn’t fix the issue.

I noticed that there are two TinyMCE directories (different names) and one has extra files in it.

Should I delete everything, then reupload? It’s now 4.8.3 but I don’t know how the extra files affect this. And they are only in the “tiny_mce” directory.
[cid:image001.png@01D44B58.16EAD140]

John

**Comment by uiwwebteam** [comment]
I've created a ticket with CMS vendor that added this to our site. Hopefully, it'll have better luck than I did.

**Comment by bklups** [comment]
@uiwwebteam I can't reproduce the sign in step.
I can't login in (with google) to see submit form.

**Comment by uiwwebteam** [comment]
Benjamin,

Thanks for responding. I've escalated this to the CMS vendor for its help since it originally set this up.

My thought is that this was working fine until it didn't. It's possible they may have done something on the backend with telling me and that broke it.

-John

Sent from my iPhone

On Sep 14, 2018, at 04:19, Benjamin Klups <notifications@github.com<mailto:notifications@github.com>> wrote:


@uiwwebteam<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fuiwwebteam&data=02%7C01%7Cwebteam%40uiwtx.edu%7C5d55c275cab24f8dffd708d61a232be4%7C0625d309c5bc41209828ea3d7071af19%7C0%7C0%7C636725135701620994&sdata=AVAGeu0Bib6A%2BCPyfjNnsAN0pLbHnWqeN%2BzJ3d24hRQ%3D&reserved=0> I can't reproduce the sign in step.
I can't login in (with google) to see submit form.
