### ISSUE TITLE
Facebook Login

### ISSUE THREAD

**Issue by dvolsysop** [asdfdotdev/Helios-Calendar#6]
Version 3 - Facebook Login seems to have just stopped working in the last 2 days.  facebook.php redirect goes back to main calendar page displaying http://www.philadelphiadance.org/tango/index.php#_=_

**Comment by dvolsysop** [comment]
One possible suspect for why the call to get the token may fail causing the call to get user data to return empty could be line 33:
$code = cIn(strip_tags($_GET['code']));

Not sure why using cIn method and then strip_tags on the `code` that came back for requesting an auth token. Not sure why potentially strip characters from an access code. On top of that, that cIn() method uses mysql_real_escape_string which changes behavior based on the database connection and its charsets etc. If facebook changed their allowed `code` characters then it could strip it incorrectly causing the request for a token to fail. Additionally, on line 34 when it requests the token with the possibly mutated code, it doesn't urlencode() it like the others so characters may be misinterpreted that way as well.

Anyway, at a loss on this beyond where I am seeing the code get stuck.  Any help to restore this function ASAP would be appreciated.

**Comment by dvolsysop** [comment]
This is apparently happening elsewhere as well as when seeing if this function is working on other sites using helios and hosted on servers other than mine, the same facebook login issue crops up.  Twitter and Google logins still work fine.

**Comment by bklups** [comment]
I have the same bug.
Do you have an idea start on how to solve it, i will take time to correct it but i don't know how to begin
