### ISSUE TITLE
Improved database support.

### ISSUE THREAD

**Issue by chrislarrycarl** [asdfdotdev/Helios-Calendar#7]
Should use PDO but be sufficiently abstracted as to allow for future support of db servers beyond just MySQL/MariaDB.

**Comment by chrislarrycarl** [comment]
The [database class](https://github.com/chrislarrycarl/cl_database) is now (mostly) ready and should significantly improve Helios' database support. Next step is integration.

**Comment by chrislarrycarl** [comment]
PDO support has been shelved in favor of the mysqli extension support contributed in https://github.com/christopherldotcom/Helios-Calendar/pull/24

**Comment by rdev5** [comment]
I would be particularly interested in adding support for Microsoft SQL Server. Is this currently supported, or do you need help with this feature?
